name: Build and Deploy Blazor WASM

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
      - name: Publish .NET Core Project
        run: dotnet publish pwa/CarnaCode.Presentation/CarnaCode.Presentation.csproj -c Release --output build
      - name: Move content from wwwroot to root
        run: |
          mv build/wwwroot/* build/
          rm -rf build/wwwroot
      - name: Find and change base-tag in index.html
        run: |
          INDEX_FILE=$(find build -type f -name "index.html")
          if [ -n "$INDEX_FILE" ]; then
            sed -i 's/<base href="\/" \/>/<base href="\/Carnacode\/" \/>/g' "$INDEX_FILE"
          else
            echo "index.html not found."
            exit   1
          fi
      - name: Create .nojekyll file
        run: touch build/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
