name: Build and Deploy Blazor WASM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"

      - name: Publish .NET Core Project
        run: dotnet publish pwa/CarnaCode.Presentation/CarnaCode.Presentation.csproj -c Release -o ./publish --nologo

      - name: Move content to root
        run: |
          mv ./publish/wwwroot/* ./publish/
          rmdir ./publish/wwwroot

      - name: Create .nojekyll file
        run: touch ./publish/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish # Path to the publish directory
          publish_branch: gh-pages # The branch you want to deploy to
