name: Build and Deploy Blazor WASM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"

      - name: Change working directory to CarnaCode.Presentation
        run: echo "Changing directory to $(Build.Repository.LocalPath)/pwa/CarnaCode.Presentation" && cd pwa/CarnaCode.Presentation

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Blazor WebAssembly app
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish # Caminho para o diretório de publicação
