name: Build and Deploy Blazor WASM

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"

      - name: Publish .NET Core Project
        run: dotnet publish pwa/CarnaCode.Presentation/CarnaCode.Presentation.csproj -c Release -o ./publish --nologo

      - name: Change base-tag in index.html from / to Carnacode
        run: sed -i 's/<base href="\/" \/>/<base href="\/Carnacode\/" \/>/g' ./publish/index.html

      - name: Create .nojekyll file
        run: touch ./publish/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: publish
